#!/bin/busybox ash
set -e
# use only full paths for non-builtins to avoid problems when only memlocked programs are available
DMSETUP=/sbin/dmsetup
GETSIZE="/sbin/blockdev --getsz"

mode="$1"
device="$2"
target="$3"

getdev() {
	look_for="$1"
	while read dev tgt; do
		if [ "$tgt" = "$look_for" ]; then
			echo "$dev";
			return
		fi
	done < /etc/switchblocktab
}

if [ "$mode" = "-r" ]; then
	exec $DMSETUP remove --deferred "$device"
fi

# given only a target (when called from udev rules), find device name in switchblocktab
if ! [ -n "$device" ]; then
	device="$(getdev "$target")"
	# no device found? target not ours
	[ -n "$device" ] || exit 0
fi

# assume UUID if target isn't a file
[ -e "$target" ] || target="/dev/disk/by-uuid/$target"

if ! [ -e "$target" ]; then
	echo "$0: $target doesn't exist" >&2
	exit 1
fi

case "$mode" in
-s) # set
	if ! $DMSETUP info "$device" >/dev/null 2>&1; then
		# create if not exists
		$DMSETUP create "$device" --notable
	fi
	$DMSETUP load "$device" --table "0 $($GETSIZE "$target") linear $target 0"
	$DMSETUP resume "$device"
	;;
-f) # freeze
	# user may call switchblock -r if they don't want the device anymore
	$DMSETUP info "$device" >/dev/null 2>&1 && $DMSETUP suspend --nolockfs --noflush "$device"
	;;
*)
	exit 1
	;;
esac
