#!/bin/sh -e
PREREQ="udev dmsetup"
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/dmsetup /sbin
copy_exec /sbin/blockdev /sbin
cp /lib/udev/switchblock "${DESTDIR}/sbin"
cp /etc/switchblocktab "${DESTDIR}/etc"
