#!/bin/sh -e
PREREQ="udev dmsetup"
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/dmsetup /sbin
copy_exec /sbin/blockdev /sbin
cp /lib/udev/rules.d/61-switchblock-activation.rules "${DESTDIR}/lib/udev/rules.d/"
cp /lib/udev/switchblock "${DESTDIR}/lib/udev/"
cp /etc/switchblocktab "${DESTDIR}/etc/"
